[package]
name = "fit-launcher-torrent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
aria2-ws = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
librqbit = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
directories = { workspace = true }
fit-launcher-ui-automation = { workspace = true }
fit-launcher-config = { workspace = true }
