name: 'publish'

on:
    workflow_dispatch:  # Manual trigger only
#   push:
#     branches:
#       - master
#     paths:
#       - 'src/**'
#       - 'src-tauri/**'
      
jobs:
  publish-tauri:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm' 

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@1.91.1

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Get latest aria2 tag
        id: get-tag
        shell: bash
        run: |
          TAG=$( curl -H "Authorization: Bearer "${{ secrets.GITHUB_TOKEN }} -s \
              https://api.github.com/repos/mokurin000/aria2c-windows-hide-console/releases/latest |
              jq -r '.tag_name'
          )
          TAG_VER=$(echo "$TAG" | sed 's/release-//')
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "tag_ver=${TAG_VER}" >> $GITHUB_OUTPUT

      - name: Download binaries
        shell: bash
        run: |
          curl -L -o 64bit.zip "https://github.com/mokurin000/aria2c-windows-hide-console/releases/download/${{ steps.get-tag.outputs.tag }}/aria2-${{ steps.get-tag.outputs.tag_ver }}-win-64bit-build1.zip"

      - name: Extract aria2c.exe
        shell: powershell
        run: |
          Expand-Archive -Path 64bit.zip -DestinationPath .
          Move-Item aria2-${{ steps.get-tag.outputs.tag_ver }}-win-64bit-build1/aria2c.exe ./src-tauri/binaries/aria2c-x86_64-pc-windows-msvc.exe
          Remove-Item 64bit.zip

      - name: install frontend dependencies
        run: npm install # change this to npm or pnpm depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY : ${{  secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD : ${{secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD}}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ''
